# Generated by Django 5.2.8 on 2025-11-26 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_logins', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('labs_run', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'unique_together': {('date', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LESSON_COMPLETE', 'Lesson Completed'), ('LAB_START', 'Lab Started'), ('PROJECT_SUBMIT', 'Project Submitted'), ('PAGE_VIEW', 'Page View')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_676ab6_idx'), models.Index(fields=['school', 'timestamp'], name='analytics_e_school__7ee108_idx')],
            },
        ),
    ]
