# Generated by Django 5.2.8 on 2025-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.IntegerField(default=1, help_text='1-12 representing grade level'),
        ),
    ]
