# Generated by Django 5.2.8 on 2025-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='environment_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
